DROP SCHEMA IF EXISTS PROJECT_DB;
CREATE SCHEMA PROJECT_DB;

USE PROJECT_DB;

DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE IF NOT EXISTS EMPLOYEE (
EMP_ID varchar(10) NOT NULL, 
MEMBERSHIP_ID varchar(10) NOT NULL, 
FNAME varchar(50) NOT NULL,
MNAME varchar(50),
LNAME varchar(50) NOT NULL,
ADDRESS varchar(500) NOT NULL,
GENDER varchar(10) NOT NULL,
START_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
DOB datetime,
AGE bigint(5),
EMP_TYPE varchar(50) NOT NULL,
PRIMARY KEY (EMP_ID))ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DROP TRIGGER IF EXISTS INSERT_PREMIUM;
DELIMITER $$
CREATE TRIGGER INSERT_PREMIUM BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
	INSERT INTO PREMIUM (MEMBERSHIP_ID, FREE_DLVRYS) VALUES (NEW.MEMBERSHIP_ID, 20);
END$$
DELIMITER ;

DESC EMPLOYEE;

DROP TRIGGER IF EXISTS trig_age_emp_check;
DELIMITER $$
CREATE TRIGGER trig_age_emp_check BEFORE INSERT ON EMPLOYEE
FOR EACH ROW 
BEGIN 
IF (NEW.AGE > 18) = 0 THEN 
  SIGNAL SQLSTATE '12345'
     SET MESSAGE_TEXT = 'WRONG AGE!';
END IF; 

IF (NEW.EMP_ID REGEXP 'E[0-9]{3}') = 0 THEN 
  SIGNAL SQLSTATE '12345'
     SET MESSAGE_TEXT = 'WRONG EMP ID!';
END IF; 

END$$
DELIMITER ;

DROP TABLE IF EXISTS PHONE;
CREATE TABLE IF NOT EXISTS PHONE (
PH_ID varchar(10) NOT NULL,
PHONE_NUMBER bigint(11) NOT NULL,
PRIMARY KEY (PH_ID, PHONE_NUMBER),
CONSTRAINT PHONE_EMP FOREIGN KEY (PH_ID) REFERENCES EMPLOYEE(EMP_ID) ON UPDATE CASCADE)ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC PHONE;

DROP TABLE IF EXISTS MANAGER;
CREATE TABLE IF NOT EXISTS MANAGER (
MID varchar(10) NOT NULL,
AREA varchar(60) NOT NULL,
PRIMARY KEY (MID),
CONSTRAINT MANAGER_EMP FOREIGN KEY (MID) REFERENCES EMPLOYEE(EMP_ID) ON UPDATE CASCADE)ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC MANAGER;

DROP TABLE IF EXISTS STAFF;
CREATE TABLE IF NOT EXISTS STAFF (
STF_ID varchar(10) NOT NULL,
PRIMARY KEY (STF_ID),
CONSTRAINT STAFF_EMP FOREIGN KEY (STF_ID) REFERENCES EMPLOYEE(EMP_ID)  ON UPDATE CASCADE)ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC STAFF;

DROP TABLE IF EXISTS DELIVERER;
CREATE TABLE IF NOT EXISTS DELIVERER (
DLVER_ID varchar(10) NOT NULL,
SUPERVISOR_ID varchar(10) NOT NULL,
NUM_DEL int(10) NOT NULL,
PRIMARY KEY (DLVER_ID),
CONSTRAINT DEL_EMP FOREIGN KEY (DLVER_ID) REFERENCES EMPLOYEE(EMP_ID) ON UPDATE CASCADE,
CONSTRAINT DEL_MNGR FOREIGN KEY (SUPERVISOR_ID) REFERENCES MANAGER(MID) ON UPDATE CASCADE)ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC DELIVERER;

DROP TABLE IF EXISTS CONTRACT;
CREATE TABLE IF NOT EXISTS CONTRACT (
AREA_MNGR_ID varchar(10) NOT NULL,
SHOP_ID varchar(10) NOT NULL,
START_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
TENURE int(10) NOT NULL,
PRIMARY KEY (AREA_MNGR_ID, SHOP_ID),
CONSTRAINT CONTRACT_MNGR FOREIGN KEY (AREA_MNGR_ID) REFERENCES MANAGER(MID) ON UPDATE CASCADE)ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC CONTRACT;

DROP TABLE IF EXISTS VHCL_INFO;
CREATE TABLE IF NOT EXISTS VHCL_INFO (
DEL_ID varchar(10) NOT NULL,
PLATE_NO varchar(10) NOT NULL,
VCOLOR varchar(10) NOT NULL,
VMAKER varchar(10) NOT NULL,
VMODEL varchar(10) NOT NULL,
PRIMARY KEY (DEL_ID, PLATE_NO),
CONSTRAINT VHCL_INFO_DELIVERER FOREIGN KEY (DEL_ID) REFERENCES DELIVERER(DLVER_ID) ON UPDATE CASCADE)ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC VHCL_INFO;

DROP TABLE IF EXISTS SHOP;
CREATE TABLE IF NOT EXISTS SHOP (
SHOP_ID varchar(10) NOT NULL,
SHOP_NAME varchar(50) NOT NULL,
ZIPCODE int(5) NOT NULL,
AREA varchar(50) NOT NULL,
PHONE bigint(11) NOT NULL,
OPEN_TIME time NOT NULL,
CLOSE_TIME time NOT NULL,
REVIEWS varchar(100) NOT NULL,
RATING int(5) NOT NULL,
SHOP_TYPE varchar(20) NOT NULL,
PRIMARY KEY (SHOP_ID))ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC SHOP;

ALTER TABLE CONTRACT ADD CONSTRAINT CONTRACT_SHOP FOREIGN KEY (SHOP_ID) REFERENCES SHOP(SHOP_ID) ON UPDATE CASCADE;

DROP TABLE IF EXISTS PROMOTION;
CREATE TABLE IF NOT EXISTS PROMOTION (
PROMOCODE varchar(20) NOT NULL,
SHOP_ID varchar(10) NOT NULL,
STARTDATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
PROMO_DESC varchar(100) NOT NULL,
PRIMARY KEY (PROMOCODE),
CONSTRAINT PROMOTION_SHOP FOREIGN KEY (SHOP_ID) REFERENCES SHOP(SHOP_ID) ON UPDATE CASCADE)ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC PROMOTION;

DROP TABLE IF EXISTS RESTAURANT;
CREATE TABLE IF NOT EXISTS RESTAURANT (
SHOP_ID varchar(10) NOT NULL,
PRIMARY KEY (SHOP_ID),
CONSTRAINT RESTAURANT_SHOP FOREIGN KEY (SHOP_ID) REFERENCES SHOP(SHOP_ID) ON UPDATE CASCADE)ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC RESTAURANT;

DROP TABLE IF EXISTS SUPERMARKET;
CREATE TABLE IF NOT EXISTS SUPERMARKET (
SHOP_ID varchar(10) NOT NULL,
PRIMARY KEY (SHOP_ID),
CONSTRAINT SUPERMARKET_SHOP FOREIGN KEY (SHOP_ID) REFERENCES SHOP(SHOP_ID) ON UPDATE CASCADE)ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC SUPERMARKET;

DROP TABLE IF EXISTS CUISINE;
CREATE TABLE IF NOT EXISTS CUISINE (
SHOP_ID varchar(10) NOT NULL,
CUISINE_TYPE varchar(20) NOT NULL,
PRIMARY KEY (SHOP_ID, CUISINE_TYPE),
CONSTRAINT CUISINE_RESTAURANT FOREIGN KEY (SHOP_ID) REFERENCES RESTAURANT(SHOP_ID) ON UPDATE CASCADE)ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC CUISINE;

DROP TABLE IF EXISTS FOOD_ITEM;
CREATE TABLE IF NOT EXISTS FOOD_ITEM (
SHOP_ID varchar(10) NOT NULL,
ITEM_ID varchar(20) NOT NULL,
FOOD_NAME varchar(50) NOT NULL,
FOOD_DESC varchar(100) NOT NULL,
PRICE float(10) NOT NULL,
PRIMARY KEY (SHOP_ID, ITEM_ID),
CONSTRAINT FOOD_ITEM_RESTAURANT FOREIGN KEY (SHOP_ID) REFERENCES RESTAURANT(SHOP_ID) ON UPDATE CASCADE)ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC FOOD_ITEM;

DROP TABLE IF EXISTS SELLS;
CREATE TABLE IF NOT EXISTS SELLS (
SHOP_ID varchar(10) NOT NULL,
PROD_ID varchar(10) NOT NULL,
QUANTITY int(10) NOT NULL,
PRICE int(10) NOT NULL,
PRIMARY KEY (SHOP_ID, PROD_ID),
CONSTRAINT SELLS_SUPERMARKET FOREIGN KEY (SHOP_ID) REFERENCES SUPERMARKET(SHOP_ID) ON UPDATE CASCADE)ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC SELLS;

DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE IF NOT EXISTS PRODUCT (
PROD_ID varchar(10) NOT NULL,
PROD_NAME varchar(50) NOT NULL,
PROD_DESC varchar(50) NOT NULL,
PRIMARY KEY (PROD_ID))ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC PRODUCT;

ALTER TABLE SELLS ADD CONSTRAINT SELLS_PRODUCT FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID) ON UPDATE CASCADE;

DROP TABLE IF EXISTS DELIVERY;
CREATE TABLE IF NOT EXISTS DELIVERY (
ORDER_ID varchar(10) NOT NULL,
DLVER_ID varchar(10) NOT NULL,
PRIMARY KEY (ORDER_ID),
CONSTRAINT DELIVERY_DELIVERER FOREIGN KEY (DLVER_ID) REFERENCES DELIVERER(DLVER_ID) ON UPDATE CASCADE)ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC DELIVERY;

DROP TABLE IF EXISTS ORDERS;
CREATE TABLE IF NOT EXISTS ORDERS (
ORDER_ID varchar(10) NOT NULL,
PAYMENT_ID varchar(10) NOT NULL,
PAYMENT_TYPE varchar(20) NOT NULL,
PAYMENT_TIME datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
CONFIRMATION bool NOT NULL,
ORDER_DETAILS varchar(50) NOT NULL,
PRIMARY KEY (ORDER_ID))ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC ORDERS;

ALTER TABLE DELIVERY ADD CONSTRAINT DELIVERY_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON UPDATE CASCADE;

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE IF NOT EXISTS CUSTOMER (
CUST_ID varchar(10) NOT NULL,
FNAME varchar(50) NOT NULL,
MNAME varchar(50),
LNAME varchar(50) NOT NULL,
PHONENUMBER bigint(11) NOT NULL,
JOIN_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (CUST_ID))ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC CUSTOMER;

DROP TABLE IF EXISTS DELADDRESS;
CREATE TABLE IF NOT EXISTS DELADDRESS (
CUST_ID varchar(10) NOT NULL,
ADDRESS varchar(50) NOT NULL,
PRIMARY KEY (CUST_ID, ADDRESS),
CONSTRAINT DELADDRESS_CUSTOMER FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID) ON UPDATE CASCADE)ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC DELADDRESS;

DROP TABLE IF EXISTS PAYMENTINFO;
CREATE TABLE IF NOT EXISTS PAYMENTINFO (
CUST_ID varchar(10) NOT NULL,
PAYMENT_DETAILS varchar(50) NOT NULL,
PRIMARY KEY (CUST_ID, PAYMENT_DETAILS),
CONSTRAINT PAYMENTINFO_CUSTOMER FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID) ON UPDATE CASCADE)ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC PAYMENTINFO;

DROP TABLE IF EXISTS ORDINARY_CUST;
CREATE TABLE IF NOT EXISTS ORDINARY_CUST (
CUST_ID varchar(10) NOT NULL,
PRIMARY KEY (CUST_ID),
CONSTRAINT ORDINARY_CUST_CUSTOMER FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID) ON UPDATE CASCADE)ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC ORDINARY_CUST;

DROP TRIGGER IF EXISTS INSERT_CUST_PREMIUM;
DELIMITER $$
CREATE TRIGGER INSERT_CUST_PREMIUM BEFORE INSERT ON SILVER_CUST
FOR EACH ROW
BEGIN
	INSERT INTO PREMIUM (MEMBERSHIP_ID, FREE_DLVRYS) VALUES (NEW.MEMBERSHIP_ID, 20);
END$$
DELIMITER ;

DROP TABLE IF EXISTS SILVER_CUST;
CREATE TABLE IF NOT EXISTS SILVER_CUST (
CUST_ID varchar(10) NOT NULL,
MEMBERSHIP_ID varchar(10),
ISSUE_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (CUST_ID),
CONSTRAINT SILVER_CUST_CUSTOMER FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID) ON UPDATE CASCADE)ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC SILVER_CUST;

DROP TABLE IF EXISTS PREMIUM;
CREATE TABLE IF NOT EXISTS PREMIUM (
MEMBERSHIP_ID varchar(10) NOT NULL,
FREE_DLVRYS int(10) NOT NULL,
PRIMARY KEY (MEMBERSHIP_ID))ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC PREMIUM;

ALTER TABLE SILVER_CUST ADD CONSTRAINT SILVER_CUST_PREMIUM FOREIGN KEY (MEMBERSHIP_ID) REFERENCES PREMIUM(MEMBERSHIP_ID) ON UPDATE CASCADE;

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMP_PREMIUM FOREIGN KEY (MEMBERSHIP_ID) REFERENCES PREMIUM(MEMBERSHIP_ID) ON UPDATE CASCADE;

DROP TABLE IF EXISTS ORDER_RELATION;
CREATE TABLE IF NOT EXISTS ORDER_RELATION (
ORDER_ID varchar(10) NOT NULL,
CUST_ID varchar(10) NOT NULL,
PROMOCODE varchar(25),
SHOP_ID varchar(10) NOT NULL,
PRIMARY KEY (ORDER_ID),
CONSTRAINT ORDER_RELATION_CUSTOMER FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID) ON UPDATE CASCADE,
CONSTRAINT ORDER_RELATION_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON UPDATE CASCADE,
CONSTRAINT ORDER_RELATION_SHOP FOREIGN KEY (SHOP_ID) REFERENCES SHOP(SHOP_ID) ON UPDATE CASCADE,
CONSTRAINT ORDER_RELATION_SHOPID_PROMO FOREIGN KEY (PROMOCODE) REFERENCES PROMOTION(PROMOCODE) ON UPDATE CASCADE)ENGINE=InnoDB AUTO_INCREMENT=169 DEFAULT CHARSET=utf8;

DESC ORDER_RELATION;