USE PROJECT_DB;

/* 1. Annual Top Customers: This view returns the First Name, Last Name, Total Order
Amount of the customers who paid top 3 total amount of orders (in terms of total
balance in the orders) in past 1 year. */
CREATE VIEW ANNUAL_TOP_CUSTOMERS
AS
SELECT FNAME, LNAME, SUM(CAST(SUBSTRING_INDEX(ORDER_DETAILS,'$',-1) AS UNSIGNED)) AS TOTAL
FROM CUSTOMER AS C
INNER JOIN ORDER_RELATION AS ORD USING (CUST_ID)
INNER JOIN ORDERS AS ORDS USING (ORDER_ID)
WHERE ORDS.PAYMENT_TIME >= DATE_SUB(curdate(), INTERVAL 1 YEAR)
GROUP BY C.CUST_ID
ORDER BY TOTAL DESC
LIMIT 3;

/* 2. Popular Restaurant Type: This view returns the Type of restaurants that have the most
number of orders in past 1 year */ 

CREATE VIEW POPULAR_RESTAURANT_TYPE
AS
SELECT CUS.CUISINE_TYPE, COUNT(*) ORDR_CNT, SUM(CAST(SUBSTRING_INDEX(ORDER_DETAILS,'$',-1) AS UNSIGNED)) AS TOTAL_ORDER_VALUE
FROM ORDER_RELATION AS ORD
INNER JOIN RESTAURANT AS RES USING (SHOP_ID)
INNER JOIN CUISINE AS CUS USING (SHOP_ID)
INNER JOIN ORDERS AS ORDS USING (ORDER_ID)
WHERE ORDS.PAYMENT_TIME >= DATE_SUB(curdate(), INTERVAL 1 YEAR)
GROUP BY CUS.CUISINE_TYPE
ORDER BY ORDR_CNT DESC; 

/* 3. Potential Silver Member: This view returns the information of the customers (not a
silver member yet) who have placed orders more than 10 times in the past 1 month */ 

CREATE VIEW POTENTIAL_SILVER_MEMBER
AS
SELECT ORD.CUST_ID, COUNT(*) AS ORDR_CNT
FROM ORDER_RELATION AS ORD 
INNER JOIN ( 
	SELECT CUST_ID FROM CUSTOMER 
	WHERE CUST_ID NOT IN (
		SELECT CUST_ID
		FROM SILVER_CUST
	)
) AS NSLVR USING (CUST_ID)
INNER JOIN ORDERS AS ORDS USING (ORDER_ID)
WHERE ORDS.PAYMENT_TIME >= DATE_SUB(curdate(), INTERVAL 1 YEAR)
GROUP BY ORD.CUST_ID
HAVING ORDR_CNT >= 10
ORDER BY ORDR_CNT DESC;

/* 4. Best Area Manager: This view returns the information of the area manager who
successfully made the most number of contracts with shops in her/his working area in
past 1 year */ 

CREATE VIEW CONTRACTS_AREA
AS
SELECT CNTRT.AREA_MNGR_ID, MNGR.AREA, COUNT(*) TCNTR
FROM CONTRACT AS CNTRT
	INNER JOIN MANAGER MNGR
    ON CNTRT.AREA_MNGR_ID = MNGR.MID
    INNER JOIN SHOP SHP
    ON CNTRT.SHOP_ID = SHP.SHOP_ID
WHERE MNGR.AREA = SHP.AREA AND CNTRT.START_DATE >= DATE_SUB(curdate(), INTERVAL 1 YEAR)
GROUP BY CNTRT.AREA_MNGR_ID
ORDER BY TCNTR DESC;

CREATE VIEW BEST_AREA_MANAGER
AS
SELECT CA.AREA_MNGR_ID, CA.AREA, CA.TCNTR
FROM CONTRACTS_AREA as CA
WHERE (	SELECT COUNT(*) 
        FROM CONTRACTS_AREA as AC
        WHERE AC.AREA = CA.AREA AND AC.TCNTR >= CA.TCNTR) <= 1;

/* 5. Top Restaurants: This view returns the top restaurant that have the most orders in past 1
month for each restaurant type */ 

CREATE VIEW POPULAR_RESTAURANT
AS SELECT ORD.SHOP_ID, CUS.CUISINE_TYPE, COUNT(*) ORDCNT
FROM ORDER_RELATION AS ORD
INNER JOIN RESTAURANT RES USING (SHOP_ID)
INNER JOIN CUISINE CUS USING (SHOP_ID)
INNER JOIN ORDERS AS ORDS USING (ORDER_ID)
WHERE ORDS.PAYMENT_TIME >= DATE_SUB(curdate(), INTERVAL 1 MONTH)
GROUP BY ORD.SHOP_ID, CUS.CUISINE_TYPE
ORDER BY ORDCNT DESC;

CREATE VIEW TOP_RESTAURANTS
AS SELECT PR.SHOP_ID, PR.CUISINE_TYPE, PR.ORDCNT
FROM POPULAR_RESTAURANT as PR
WHERE (	SELECT COUNT(*) FROM POPULAR_RESTAURANT as RP WHERE RP.CUISINE_TYPE = PR.CUISINE_TYPE AND RP.ORDCNT >= PR.ORDCNT ) <= 1
LIMIT 1;